import {
  MdCalendarToday,
  MdCategory,
  MdAttachMoney,
  MdNotes,
  MdTag,
} from "react-icons/md"

export const expenseFields = [
  {
    name: "date",
    label: "Date of Transaction",
    type: "date",
    required: true,
    icon: MdCalendarToday,
    colSpan: 1,
  },
  {
    name: "category",
    label: "Expense Category",
    type: "select",
    required: true,
    icon: MdCategory,
    colSpan: 1,
    options: [
      { value: "", label: "Select category...", disabled: true },
      { value: "supplies", label: "School Supplies" },
      { value: "maintenance", label: "Maintenance & Repairs" },
      { value: "events", label: "Events & Activities" },
      { value: "utilities", label: "Utilities" },
      { value: "salaries", label: "Salaries & Wages" },
      { value: "other", label: "Other" },
    ],
  },
  {
    name: "amount",
    label: "Total Amount",
    type: "number",
    required: true,
    icon: MdAttachMoney,
    colSpan: 1,
    placeholder: "0.00",
    min: 0,
    step: "0.01",
  },
  {
    name: "reference",
    label: "Reference / Invoice No.",
    type: "text",
    required: false,
    icon: MdTag,
    colSpan: 1,
    placeholder: "e.g. INV-2024-001",
  },
  {
    name: "description",
    label: "Description / Notes",
    type: "textarea",
    required: false,
    icon: MdNotes,
    colSpan: 2,
    placeholder: "Enter details about the expense...",
    rows: 3,
  },
]